<?php
/**
 * The template for displaying the footer on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/footer.scss.
 * The "Footer Columns" generated by PHP can be configured in functions.php.
 *
 * Contains the footer of the site as well as WP's required code and the closing body and HTML tags.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage BunnyFooFoo
 * @since 1.0.0
 */
?>

<!--Start Footer-->
<footer class="footer">
    <div class="grid grid-cols-12 ">
        <div class="col-span-12">
            <div class="text-center">
                <h1 class = "text-xl">You Belong Here.</h1>
                <div class = "font-bold"><a href="/">Home</a> | <a href="https://foothillschurch.com/">Foothills Church</a></div>
            </div>
        </div>
    </div>
</footer>
<!--End Footer-->


<!--Wordpress Requires This-->
<?php wp_footer(); ?>

</body>
</html>

